/**
 * GitHub Issue Manager
 * Handles creation and duplicate detection of GitHub issues for test failures
 */

interface GitHubConfig {
  token?: string;
  owner: string;
  repo: string;
}

interface FailureInfo {
  testName: string;
  testPath: string;
  browser: string;
  errorMessage: string;
  stackTrace: string;
  timestamp: string;
  duration: number;
  retries: number;
}

interface GitHubIssue {
  number: number;
  title: string;
  state: string;
  body: string;
}

interface GitHubApiErrorItem {
  field?: string;
  code?: string;
  message?: string;
}

interface GitHubApiErrorResponse {
  message?: string;
  errors?: Array<GitHubApiErrorItem | string>;
}

export class GitHubIssueManager {
  private config: GitHubConfig;
  private baseUrl = 'https://api.github.com';
  private issueCache: Map<string, GitHubIssue[]> = new Map();

  constructor(config: GitHubConfig) {
    this.config = config;
  }

  isConfigured(): boolean {
    return !!(
      this.config.token &&
      this.config.owner &&
      this.config.repo
    );
  }

  /**
   * Create a GitHub issue if one doesn't already exist for the same test
   * @returns true if issue was created, false if it already exists
   */
  async createIssueIfNotExists(failureInfo: FailureInfo): Promise<boolean> {
    if (!this.isConfigured()) {
      throw new Error('GitHub configuration incomplete');
    }

    const issueTitle = this.generateIssueTitle(failureInfo);
    
    // Check for existing open issues
    const existingIssue = await this.findExistingIssue(issueTitle);
    
    if (existingIssue) {
      console.log(
        `[GitHub Issue Manager] Found existing issue #${existingIssue.number}: ${issueTitle}`
      );
      // Update the existing issue with a comment about new failure
      await this.updateIssueWithFailure(existingIssue.number, failureInfo);
      return false;
    }

    // Create new issue
    const issueBody = this.generateIssueBody(failureInfo);
    const issue = await this.createIssue(issueTitle, issueBody, failureInfo);
    
    return !!issue;
  }

  private generateIssueTitle(failureInfo: FailureInfo): string {
    const rawTitle = `Test Failure: ${failureInfo.testName} [${failureInfo.browser}]`;
    // GitHub issue titles have a max length of 256 chars.
    return rawTitle.length > 250 ? `${rawTitle.slice(0, 247)}...` : rawTitle;
  }

  private generateIssueBody(failureInfo: FailureInfo): string {
    const timestamp = new Date(failureInfo.timestamp).toLocaleString();
    
    const body = `## Test Failure Report

**Test Name:** \`${failureInfo.testName}\`

**Browser:** ${failureInfo.browser}

**Test File:** \`${failureInfo.testPath}\`

**Timestamp:** ${timestamp}

**Duration:** ${failureInfo.duration}ms

**Retries:** ${failureInfo.retries}

---

## Error Message

\`\`\`
${failureInfo.errorMessage}
\`\`\`

---

## Stack Trace

\`\`\`
${this.truncateStackTrace(failureInfo.stackTrace)}
\`\`\`

---

## Steps to Reproduce

1. Run the test suite: \`npm test\`
2. The test \`${failureInfo.testName}\` should fail on \`${failureInfo.browser}\` browser
3. Check the detailed error above

---

**Auto-generated by GitHub Issue Reporter**
Created: ${new Date().toISOString()}`;

    return body;
  }

  private truncateStackTrace(stackTrace: string, maxLines: number = 30): string {
    const lines = stackTrace.split('\n');
    if (lines.length > maxLines) {
      return lines.slice(0, maxLines).join('\n') + `\n... (truncated, ${lines.length - maxLines} more lines)`;
    }
    return stackTrace;
  }

  private async findExistingIssue(title: string): Promise<GitHubIssue | null> {
    try {
      const searchQuery = `repo:${this.config.owner}/${this.config.repo} in:title "${title}" state:open type:issue`;
      
      const response = await fetch(
        `${this.baseUrl}/search/issues?q=${encodeURIComponent(searchQuery)}`,
        {
          headers: {
            Accept: 'application/vnd.github.v3+json',
            Authorization: `token ${this.config.token}`,
          },
        }
      );

      if (!response.ok) {
        throw new Error(`GitHub API error: ${response.statusText}`);
      }

      const data = (await response.json()) as {
        items: Array<{
          number: number;
          title: string;
          state: string;
          body: string;
        }>;
      };
      
      return data.items.length > 0 ? data.items[0] : null;
    } catch (error) {
      console.error('[GitHub Issue Manager] Error searching for existing issues:', error);
      throw error;
    }
  }

  private async createIssue(
    title: string,
    body: string,
    failureInfo: FailureInfo
  ): Promise<GitHubIssue | null> {
    try {
      const assignees = process.env.GITHUB_ISSUE_ASSIGNEES
        ? process.env.GITHUB_ISSUE_ASSIGNEES
            .split(',')
            .map(a => a.trim())
            .filter(Boolean)
        : undefined;

      const basePayload: Record<string, unknown> = {
        title,
        body,
        labels: this.generateLabels(failureInfo),
        assignees,
      };

      let attempt = await this.postIssue(basePayload);

      if (
        !attempt.ok &&
        attempt.status === 422 &&
        Array.isArray(basePayload.assignees) &&
        basePayload.assignees.length > 0
      ) {
        console.warn(
          '[GitHub Issue Manager] Issue creation failed with assignees. Retrying without assignees.'
        );
        const retryPayload = {
          ...basePayload,
          assignees: undefined,
        };
        attempt = await this.postIssue(retryPayload);
      }

      if (!attempt.ok && attempt.status === 422 && Array.isArray(basePayload.labels) && basePayload.labels.length > 0) {
        console.warn(
          '[GitHub Issue Manager] Issue creation failed with labels. Retrying without labels.'
        );
        const retryPayload = {
          title,
          body,
          assignees: undefined,
        };
        attempt = await this.postIssue(retryPayload);
      }

      if (!attempt.ok) {
        const details = this.formatGitHubValidationErrors(attempt.errorData);
        throw new Error(
          `Failed to create issue: ${attempt.status} ${attempt.statusText}${details ? ` - ${details}` : ''}`
        );
      }

      const issue = attempt.data as GitHubIssue;
      console.log(
        `[GitHub Issue Manager] Created issue #${issue.number}: ${title}`
      );
      return issue;
    } catch (error) {
      console.error('[GitHub Issue Manager] Error creating issue:', error);
      throw error;
    }
  }

  private async postIssue(payload: Record<string, unknown>): Promise<{
    ok: boolean;
    status: number;
    statusText: string;
    data: unknown;
    errorData: unknown;
  }> {
    const response = await fetch(
      `${this.baseUrl}/repos/${this.config.owner}/${this.config.repo}/issues`,
      {
        method: 'POST',
        headers: {
          Accept: 'application/vnd.github.v3+json',
          Authorization: `token ${this.config.token}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(payload),
      }
    );

    const contentType = response.headers.get('content-type') || '';
    const isJson = contentType.includes('application/json');
    const body = isJson ? await response.json() : await response.text();

    return {
      ok: response.ok,
      status: response.status,
      statusText: response.statusText,
      data: response.ok ? body : null,
      errorData: response.ok ? null : body,
    };
  }

  private formatGitHubValidationErrors(errorData: unknown): string {
    if (!errorData) {
      return '';
    }

    if (typeof errorData === 'string') {
      return errorData;
    }

    const typed = errorData as GitHubApiErrorResponse;
    const message = typed.message || '';
    const errors = Array.isArray(typed.errors)
      ? typed.errors
          .map((e) => {
            if (typeof e === 'string') {
              return e;
            }

            const field = e.field ? `${e.field}: ` : '';
            const code = e.code ? `(${e.code}) ` : '';
            return `${field}${code}${e.message || ''}`.trim();
          })
          .filter(Boolean)
          .join('; ')
      : '';

    return [message, errors].filter(Boolean).join(' | ');
  }

  private async updateIssueWithFailure(
    issueNumber: number,
    failureInfo: FailureInfo
  ): Promise<void> {
    try {
      const comment = `### New Failure Detected

**Time:** ${new Date(failureInfo.timestamp).toLocaleString()}
**Browser:** ${failureInfo.browser}
**Retry Count:** ${failureInfo.retries}
**Duration:** ${failureInfo.duration}ms

\`\`\`
${failureInfo.errorMessage}
\`\`\``;

      const response = await fetch(
        `${this.baseUrl}/repos/${this.config.owner}/${this.config.repo}/issues/${issueNumber}/comments`,
        {
          method: 'POST',
          headers: {
            Accept: 'application/vnd.github.v3+json',
            Authorization: `token ${this.config.token}`,
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({ body: comment }),
        }
      );

      if (!response.ok) {
        throw new Error(`Failed to add comment: ${response.statusText}`);
      }

      console.log(
        `[GitHub Issue Manager] Added failure comment to issue #${issueNumber}`
      );
    } catch (error) {
      console.error(
        `[GitHub Issue Manager] Error updating issue #${issueNumber}:`,
        error
      );
    }
  }

  private generateLabels(failureInfo: FailureInfo): string[] {
    const labels = ['test-failure', `browser-${failureInfo.browser}`];

    // Add label for frequently failing tests
    if (failureInfo.retries > 0) {
      labels.push('flaky-test');
    }

    // Add label if test took a long time
    if (failureInfo.duration > 30000) {
      labels.push('slow-test');
    }

    return labels;
  }
}

export { FailureInfo, GitHubConfig, GitHubIssue };
